### ISSUE TITLE
Doesn't work with the last version of mosquitto

### ISSUE THREAD

**Issue by SylvainMontagny** [brocaar/chirpstack-docker#39] opened 2021-02-10 20:43 UTC
docker-compose.yml file worked perfectly until 10 days ago. The lastest version of mosquitto container leads now to this error : 
Error: Address not available  :  (https://github.com/eclipse/mosquitto/issues/2040) .

I had to use go back to eclipse-mosquitto:1.5 to make it work. 
  
mosquitto:
    image: eclipse-mosquitto:1.5
    ports:
      - 1883:1883

**Comment by GinterP** [comment] 2021-02-11 06:14
eclipse-mosquitto:2.0 has breaking changes: https://mosquitto.org/blog/2020/12/version-2-0-0-released/

In order to get this working with v2 you have to add the following settings to `mosquitto.conf`:
```
listener 1883 
allow_anonymous true
```

**Comment by brocaar** [comment] 2021-02-11 18:15
I have fixed the version to `:1.6` so that the issue is fixed for now. @GinterP would you like to make a pull-request, updating Mosquitto to v2 + adding the above config?

**Comment by GinterP** [comment] 2021-02-12 06:27
I have added a pull request: #40

**Comment by brocaar** [comment] 2021-02-12 10:38
I've merged #40 :+1:

**Closed by brocaar** 2021-02-12 10:38 UTC
