### ISSUE TITLE
MQTT 2.0 has broken docker compose

### ISSUE THREAD

**Issue by bryanmcgrane** [brocaar/chirpstack-docker#44] opened 2021-04-20 00:23 UTC
I tried to deploy the docker-compose configuration, and ran into an issue where MQTT was refusing to connection from all servers. Due the the below breaking change:

https://github.com/eclipse/mosquitto/issues/2040

I was able fix this by fixing the MQTT docker container to 1.6 via:

```
 mosquitto:
    image: eclipse-mosquitto:1.6
    ports:
      - 1883:1883

```

**Comment by GinterP** [comment] 2021-04-20 04:36
Possible duplicate of #39

**Comment by brocaar** [comment] 2021-04-20 07:42
I believe @GinterP fixed this in https://github.com/brocaar/chirpstack-docker/pull/40?

**Closed** 2021-06-29 10:51 UTC
